version: '3.8'

services: #6 services as below
#1
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html  # adding composer source code to the nginx server
      - ./nginx/nginx.conf:/etc/nginx/nginx.d/default.conf:ro
    depends_on:
      - php
      - mysql
    
#2
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # delegated= to write the data in the host in batches 
                                      # and not directly -> improves performance

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  composer: # to create the php app we need composer utility container
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  # artisan:
  # npm: